// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(

    apiKey: 'AIzaSyAXxvWE5klDHky06QekVZbZqyUMB1ZMb-Y',
    appId: '1:40116824756:web:845651d4f25a98573545e1',
    messagingSenderId: '40116824756',
    projectId: 'agriculture-helper-9f2e7',
    authDomain: 'agriculture-helper-9f2e7.firebaseapp.com',
    storageBucket: 'agriculture-helper-9f2e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB693lAAuSo1MO-0PRnV7uVfXHkaFHVOw',
    appId: '1:40116824756:android:9167a1302ac01d193545e1',
    messagingSenderId: '40116824756',
    projectId: 'agriculture-helper-9f2e7',
    storageBucket: 'agriculture-helper-9f2e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV0zGfHGO3liSB28-A1Q5Uaxioa0DeWXY',
    appId: '1:40116824756:ios:9ec502a9f7eeb9e53545e1',
    messagingSenderId: '40116824756',
    projectId: 'agriculture-helper-9f2e7',
    storageBucket: 'agriculture-helper-9f2e7.firebasestorage.app',

    iosBundleId: 'com.example.agriHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(

    apiKey: 'AIzaSyAV0zGfHGO3liSB28-A1Q5Uaxioa0DeWXY',
    appId: '1:40116824756:ios:9ec502a9f7eeb9e53545e1',
    messagingSenderId: '40116824756',
    projectId: 'agriculture-helper-9f2e7',
    storageBucket: 'agriculture-helper-9f2e7.firebasestorage.app',

    iosBundleId: 'com.example.agriHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(

    apiKey: 'AIzaSyAXxvWE5klDHky06QekVZbZqyUMB1ZMb-Y',
    appId: '1:40116824756:web:845651d4f25a98573545e1',
    messagingSenderId: '40116824756',
    projectId: 'agriculture-helper-9f2e7',
    authDomain: 'agriculture-helper-9f2e7.firebaseapp.com',
    storageBucket: 'agriculture-helper-9f2e7.firebasestorage.app',
  );
}

