// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqmxdvaeqpQsm_V0KzQbEUnLOqLZ8wtHQ',
    appId: '1:678941508467:web:3e3874109447c73bc97b06',
    messagingSenderId: '678941508467',
    projectId: 'agri-helper-9cea4',
    authDomain: 'agri-helper-9cea4.firebaseapp.com',
    storageBucket: 'agri-helper-9cea4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnUuHW0C_kVSdxYMzFlH4T5fUdPNZzZxw',
    appId: '1:678941508467:android:a26f903ca726f2b4c97b06',
    messagingSenderId: '678941508467',
    projectId: 'agri-helper-9cea4',
    storageBucket: 'agri-helper-9cea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4_-sOzBlgbTLETp98f3wBUYInmudERjI',
    appId: '1:678941508467:ios:3080a78d1bac4b58c97b06',
    messagingSenderId: '678941508467',
    projectId: 'agri-helper-9cea4',
    storageBucket: 'agri-helper-9cea4.firebasestorage.app',
    iosBundleId: 'com.example.agriHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4_-sOzBlgbTLETp98f3wBUYInmudERjI',
    appId: '1:678941508467:ios:3080a78d1bac4b58c97b06',
    messagingSenderId: '678941508467',
    projectId: 'agri-helper-9cea4',
    storageBucket: 'agri-helper-9cea4.firebasestorage.app',
    iosBundleId: 'com.example.agriHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqmxdvaeqpQsm_V0KzQbEUnLOqLZ8wtHQ',
    appId: '1:678941508467:web:9934a9f755efcc5cc97b06',
    messagingSenderId: '678941508467',
    projectId: 'agri-helper-9cea4',
    authDomain: 'agri-helper-9cea4.firebaseapp.com',
    storageBucket: 'agri-helper-9cea4.firebasestorage.app',
  );

}