name: agri_helper
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter_typeahead: ^5.2.0
  flutter:
    sdk: flutter
  image: ^4.3.0
  path: ^1.8.2
  flutter_markdown: ^0.6.10
  flutter_riverpod: ^2.4.10
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.8
  image_picker: ^1.0.7
  http: ^1.2.0
  dio: ^5.4.1
  intl: ^0.20.2
  google_maps_flutter: ^2.5.3
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1
  geolocator: ^13.0.4
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  http_parser: ^4.1.2
  modal_bottom_sheet: ^3.0.0
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.0
  lottie: ^3.1.0
  dropdown_button2: ^2.3.9
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  permission_handler: ^11.3.1
  device_info_plus: ^10.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - assets/
    - assets/lottie/
    - assets/final_2.json
    - assets/final_2_with_thumbs.json
    - assets/plants/
    - assets/disease/apple/Apple___Cedar_apple_rust/
    - assets/disease/apple/Apple___Apple_scab/
    - assets/disease/apple/Apple___Black_rot/
    - assets/disease/strawberry/Strawberry___Leaf_scorch/
    - assets/disease/rice/Sheath Blight/
    - assets/disease/rice/Leaf Blast/
    - assets/disease/rice/Bacterial Leaf Blight/
    - assets/disease/rice/Brown Spot/
    - assets/disease/rice/Leaf scald/
    - assets/disease/potato/Potato___Early_blight/
    - assets/disease/potato/Potato___Late_blight/
    - assets/disease/durian/LEAF_BLIGHT/
    - assets/disease/durian/ALLOCARIDARA_ATTACK/
    - assets/disease/durian/ALGAL_LEAF_SPOT/
    - assets/disease/durian/PHOMOPSIS_LEAF_SPOT/
    - assets/disease/pepper/Pepper_bell___Bacterial_spot/
    - assets/disease/tomato/Tomato___Target_Spot/
    - assets/disease/tomato/Tomato___Late_blight/
    - assets/disease/tomato/Tomato___Tomato_mosaic_virus/
    - assets/disease/tomato/Tomato___Leaf_Mold/
    - assets/disease/tomato/Tomato___Bacterial_spot/
    - assets/disease/tomato/Tomato___Early_blight/
    - assets/disease/tomato/Tomato___Tomato_Yellow_Leaf_Curl_Virus/
    - assets/disease/tomato/Tomato___Spider_mites Two-spotted_spider_mite/
    - assets/disease/tomato/Tomato___Septoria_leaf_spot/
    - assets/disease/mango/Bacterial Canker/
    - assets/disease/mango/Anthracnose/
    - assets/disease/mango/Powdery Mildew/
    - assets/disease/mango/Cutting Weevil/
    - assets/disease/mango/Sooty Mould/
    - assets/disease/mango/Gall Midge/
    - assets/disease/mango_fruit/Alternaria/
    - assets/disease/mango_fruit/Anthracnose/
    - assets/disease/mango_fruit/Stem end Rot/
    - assets/disease/mango_fruit/Black Mould Rot/
    - assets/disease/orange/Citrus_Canker_Diseases_Leaf_Orange/
    - assets/disease/orange/Citrus_Nutrient_Deficiency_Yellow_Leaf_Orange/
    - assets/disease/orange/Greening/
    - assets/disease/corn/Corn_(maize)___Common_rust_/
    - assets/disease/corn/Corn_(maize)___Northern_Leaf_Blight/
    - assets/disease/corn/Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot/
    - assets/disease/banana/Banana Fruit-Scarring Beetle/
    - assets/disease/banana/Anthracnose/
    - assets/disease/banana/Black and Yellow Sigatoka/
    - assets/disease/banana/Banana Skipper Damage/
    - assets/disease/banana/Chewing insect damage on banana leaf/
    - assets/disease/banana/Banana Split Peel/
    - assets/disease/grape/Grape___Black_rot/
    - assets/disease/grape/Grape___Leaf_blight_(Isariopsis_Leaf_Spot)/
    - assets/disease/grape/Grape___Esca_(Black_Measles)/
    - assets/disease/peach/Peach___Bacterial_spot/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false             
  image_path: "assets/app_icon.png"
  min_sdk_android: 21      
  remove_alpha_ios: true   
  web:
    generate: false
  windows:
    generate: false 
  macos:
    generate: false