name: agri_helper
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.10
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  image_picker: ^1.0.7
  http: ^1.2.0
  dio: ^5.4.1
  intl: ^0.20.2
  google_maps_flutter: ^2.5.3
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1
  geolocator: ^13.0.4
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
