name: agri_helper
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter_typeahead: ^5.2.0
  flutter:
    sdk: flutter
  image: ^3.2.2
  path: ^1.8.2
  flutter_markdown: ^0.6.10
  flutter_riverpod: ^2.4.10
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.8
  image_picker: ^1.0.7
  http: ^1.2.0
  dio: ^5.4.1
  intl: ^0.20.2
  google_maps_flutter: ^2.5.3
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1
  geolocator: ^13.0.4
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  http_parser: ^4.1.2
  modal_bottom_sheet: ^3.0.0
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.0
  lottie: ^3.1.0
  dropdown_button2: ^2.3.9
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  permission_handler: ^11.3.1
  device_info_plus: ^10.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - assets/
    - assets/lottie/
    - assets/final_2.json
    - assets/final_2_with_thumbs.json
    - assets/plants/